### PR TITLE
Update utils.py parse_varint(tx)

### PR DESCRIPTION
**Pull request by frstrtr**
Fix for the parse_varint(tx)
if varint>252

### CODE REVIEW

**Comment by sr-gi** [comment]
I don't think this is right.

For `0xFC` and bellow, the encoding is a single byte with no prefix (2 hex values).
For `0xFD`, it translates to 1 byte prefix plus 2 bytes data (that's 3 bytes, 6 hex values).
For `0xFE`, it translates to 1 byte prefix plus 4 bytes data (that's 5 bytes, 10 hex values).
For `0xFF`, it translates to 1 byte prefix plus 8 bytes data (that's 9 bytes, 18 hex values).

Your current approach is leaving no prefix as it was, but adding an additional byte for the prefix in the rest of the cases, while the prefix was already accounted for.

**Comment by frstrtr** [comment]
I tested this solution with witness TX (i will push it later) and if I use your approach it leads to tx.offset overshift. My solution works perfectly.
for example: txid 45a0335fa9cef557a966d4b9764b084d7342f25f889c495812c468cbba7340f9
decoderawtransaction
02000000000104564cbd188db7178dac57cf7a5fd09812c947a5cfb75d66a1a46ca27465fc21b10000000017160014c3eb4c03b0df78ffc211f72ea8d08d0eca74e281fdffffff672e57b9693ca48089016849aa809a189d75f4982422c00baf5bfa05ceb11db90100000017160014fd074bd35ce52c61f8855b61ed72c690923e5a87fdffffffbed5f7848ae630b804a6f7732059d3fc1d86df8def8a9bf014ded8c274dcffb80c000000171600140de01b667a614191920b4686dea2db8973bb35bafdffffffe58cfb3212e988e05682e4dd4530239e7913455755ea41358e6ee87e3d48692400000000171600141d9764cb5906eaa5c07a987624f93189f287971bfdffffff010065cd1d0000000017a9144d856ff4875decf91c413f194de7ec38859a7a3c87024730440220338f13d154910ceef62039753a0d3394ad6715b45bbc9945a5d1b31899a8a6b602206bb4371b204ccd1a9da759188feff7ba268540c4c0c65a2632fa9eddc14ce60a0121036b7ed62f4026d8a484640953af4490f866565875f8c4c952114aa71c42e21aac0247304402205bead2ee73bfec6fc879a185e30d1f1cf901df46cc8a7e715baf1a2d5801267102200268cca107105b7d1e40879250c1e6b08418b37773a1ceba323340c7b946fd0e012103e162a4070a16a73d44d00e66abaf639eacf48a8c38108656622d842bb7873a030247304402203e3adbee9e095153ae16b47de13a69d534aa3eb0f194e7b870be75b34c9df657022027f67be4ce4f480c8e60e51c132ec1949f887edee1c80e87e2f299b632e1290b012103803fe60d6e9497ba760ae71c7924eabdf2673c299ef2f9df4bb8c87797e6b3bd0247304402207e6160a5a90c6ea4855d71acb4803a30661001d81f754b00a786a830f7e3bbd302201a7a1b7832f716dbbd12bb378bdfe5f6172988550832a64d1d03d1e1a4cf44ae012103dd39b5b603fc1eac34a371c6f3f3a419bd2098bb7c80b45738260c9402dfdb8a73f00900

**Comment by sr-gi** [comment]
Oh, got you. The problem is not there though, but in `TX.deserialize`.

The output of `parse_varint` should be input to `decode_varint`, but `TX.deserialize` is casting that to int straight away without taking into account the prefix.

Replacing the instances of `int(parse_varint(tx), 16)` for `decode_varint(parse_varint(tx))` should do the trick.

**Comment by sr-gi** [comment]
BTW SegWit deserialisation is not part of `master`, but I added partial coverage in `split` branch a while ago, that may be a better way to start from if you're looking into do something with segwit.

**Comment by frstrtr** [comment]
It seems that in case of refactoring all int(parse_varint(tx)) to decode_varint(parse_varint(tx)) requires a lot of work, maybe better get rid of decode_varint(tx) and make all checks and changes in the parse_varint(tx) as in my patch?

**Comment by frstrtr** [comment]
> BTW SegWit deserialisation is not part of `master`, but I added partial coverage in `split` branch a while ago, that may be a better way to start from if you're looking into do something with segwit.

I didn't notice that branch, so I will check how to merge it with my fork...

**Comment by sr-gi** [comment]
> It seems that in case of refactoring all int(parse_varint(tx)) to decode_varint(parse_varint(tx)) requires a lot of work, maybe better get rid of decode_varint(tx) and make all checks and changes in the parse_varint(tx) as in my patch?

There are only 4 instances of that in the whole codebase, and they are all in `TX.deserialise`, so it should be easy enough. Besides, your current approach is doing both parsing + decoding. Removing decoding means that there is no way of decoding a varint without parsing it from a transaction.

**Comment by frstrtr** [comment]
Ok, agreed. Will you push an updated version?

**Comment by sr-gi** [comment]
Can do, but I can also accept your PR if you ammend it with the changes. Whatever you'd rather.

**Comment by frstrtr** [comment]
Ok, will push it in 1-2 days...

**Comment by frstrtr** [comment]
Emm... finished...

Unintentionally added some formatting...

**Comment by sr-gi** [comment]
Several things here:

- This should be squashed to a single commit, given that the first commits are meaningless now.
- Do not push your custom .gitignore
- The formatting should be removed, given that it creates too big of a diff for a simple 4 lines update.

I don't mind doing this final tweaks for you, just let me know.

**Comment by frstrtr** [comment]
Yes, please.

**Comment by frstrtr** [comment]
fixed in the patch-3

**Pull request closed without merging**
